### ISSUE TITLE
this.source is not a function

### ISSUE THREAD

**Issue by darylknight** [bossanova808/CommerceAusPostLookup#1]
I'm trying to implement this on a site at the moment. I've integrated the example template code from the docs but I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/1250017/15368611/5c9e1860-1d37-11e6-85e8-8c816f891e27.png)

Any ideas where I'm going wrong?

The market_states table doesn't exist anymore since Market was bought by Craft and has since turned in to Commerce. Does this plugin work with the lastest version of Craft/Commerce?

**Comment by bossanova808** [comment]
Hi Daryl

It's working fine with latest Commerce.  I just pushed an update to fix a bug with a missing state - had left out ACT (oops!).  But I don't think that's your issue here.

(You should get that update in your updates soon...but I did move the releases.json so if it doesn't show up just grab the release from here and it should work with updating from then on).

I suspect you're running in to an error of jquery-ui's autocomplete clashing with the dev-bridge one - there's some stuff about this here:
http://stackoverflow.com/questions/3308935/jquery-autocomplete-this-source-is-not-a-function-error

I think you can probably just use the autocomplete in jquery-ui but I haven't used that so I am not sure.  It may just be solveable by changing the order you load things....anyway, check out that link, and happy to try help some more on Slack.
